# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NewTask(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None):  # noqa: E501
        """NewTask - a model defined in Swagger

        :param title: The title of this NewTask.  # noqa: E501
        :type title: str
        :param description: The description of this NewTask.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'title': str,
            'description': str
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description'
        }
        self._title = title
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'NewTask':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewTask of this NewTask.  # noqa: E501
        :rtype: NewTask
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this NewTask.


        :return: The title of this NewTask.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NewTask.


        :param title: The title of this NewTask.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this NewTask.


        :return: The description of this NewTask.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this NewTask.


        :param description: The description of this NewTask.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description
