# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, description: str=None, completed: bool=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param id: The id of this Task.  # noqa: E501
        :type id: int
        :param title: The title of this Task.  # noqa: E501
        :type title: str
        :param description: The description of this Task.  # noqa: E501
        :type description: str
        :param completed: The completed of this Task.  # noqa: E501
        :type completed: bool
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'description': str,
            'completed': bool
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'completed': 'completed'
        }
        self._id = id
        self._title = title
        self._description = description
        self._completed = completed

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Task.


        :return: The id of this Task.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Task.


        :param id: The id of this Task.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Task.


        :return: The title of this Task.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Task.


        :param title: The title of this Task.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Task.


        :return: The description of this Task.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Task.


        :param description: The description of this Task.
        :type description: str
        """

        self._description = description

    @property
    def completed(self) -> bool:
        """Gets the completed of this Task.


        :return: The completed of this Task.
        :rtype: bool
        """
        return self._completed

    @completed.setter
    def completed(self, completed: bool):
        """Sets the completed of this Task.


        :param completed: The completed of this Task.
        :type completed: bool
        """

        self._completed = completed
