# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.student import Student  # noqa: F401,E501
from swagger_server import util


class StudentResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, student: Student=None):  # noqa: E501
        """StudentResponse - a model defined in Swagger

        :param message: The message of this StudentResponse.  # noqa: E501
        :type message: str
        :param student: The student of this StudentResponse.  # noqa: E501
        :type student: Student
        """
        self.swagger_types = {
            'message': str,
            'student': Student
        }

        self.attribute_map = {
            'message': 'message',
            'student': 'student'
        }
        self._message = message
        self._student = student

    @classmethod
    def from_dict(cls, dikt) -> 'StudentResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StudentResponse of this StudentResponse.  # noqa: E501
        :rtype: StudentResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this StudentResponse.

        Success message  # noqa: E501

        :return: The message of this StudentResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this StudentResponse.

        Success message  # noqa: E501

        :param message: The message of this StudentResponse.
        :type message: str
        """

        self._message = message

    @property
    def student(self) -> Student:
        """Gets the student of this StudentResponse.


        :return: The student of this StudentResponse.
        :rtype: Student
        """
        return self._student

    @student.setter
    def student(self, student: Student):
        """Sets the student of this StudentResponse.


        :param student: The student of this StudentResponse.
        :type student: Student
        """

        self._student = student
