# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StudentInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, age: int=None, email: str=None, course: str=None):  # noqa: E501
        """StudentInput - a model defined in Swagger

        :param name: The name of this StudentInput.  # noqa: E501
        :type name: str
        :param age: The age of this StudentInput.  # noqa: E501
        :type age: int
        :param email: The email of this StudentInput.  # noqa: E501
        :type email: str
        :param course: The course of this StudentInput.  # noqa: E501
        :type course: str
        """
        self.swagger_types = {
            'name': str,
            'age': int,
            'email': str,
            'course': str
        }

        self.attribute_map = {
            'name': 'name',
            'age': 'age',
            'email': 'email',
            'course': 'course'
        }
        self._name = name
        self._age = age
        self._email = email
        self._course = course

    @classmethod
    def from_dict(cls, dikt) -> 'StudentInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StudentInput of this StudentInput.  # noqa: E501
        :rtype: StudentInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this StudentInput.

        Name of the student  # noqa: E501

        :return: The name of this StudentInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this StudentInput.

        Name of the student  # noqa: E501

        :param name: The name of this StudentInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def age(self) -> int:
        """Gets the age of this StudentInput.

        Age of the student  # noqa: E501

        :return: The age of this StudentInput.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age: int):
        """Sets the age of this StudentInput.

        Age of the student  # noqa: E501

        :param age: The age of this StudentInput.
        :type age: int
        """
        if age is None:
            raise ValueError("Invalid value for `age`, must not be `None`")  # noqa: E501

        self._age = age

    @property
    def email(self) -> str:
        """Gets the email of this StudentInput.

        Email address of the student  # noqa: E501

        :return: The email of this StudentInput.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this StudentInput.

        Email address of the student  # noqa: E501

        :param email: The email of this StudentInput.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def course(self) -> str:
        """Gets the course of this StudentInput.

        Course the student is enrolled in  # noqa: E501

        :return: The course of this StudentInput.
        :rtype: str
        """
        return self._course

    @course.setter
    def course(self, course: str):
        """Sets the course of this StudentInput.

        Course the student is enrolled in  # noqa: E501

        :param course: The course of this StudentInput.
        :type course: str
        """
        if course is None:
            raise ValueError("Invalid value for `course`, must not be `None`")  # noqa: E501

        self._course = course
